services:
  mysql:
    image: mysql:8.0
    container_name: mysqlDB2
    environment:
      MYSQL_DATABASE: mysqlD2
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
