name: Vehiculos DB Backup

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar Docker
      uses: docker/setup-buildx-action@v2

    - name: Construir y levantar el contenedor
      run: docker compose up -d --build

    - name: Ejecutar el backup
      run: |
        chmod +x backups/backup.sh
        ./backups/backup.sh

    - name: Guardar respaldos en GitHub
      uses: actions/upload-artifact@v4
      with:
        name: vehiculos-backup
        path: backups/*.sql

    - name: Apagar el contenedor
      run: docker compose down
